apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app

resources:
- ../../base

patches:
- path: replica-count.yaml
- path: configmap-patch.yaml

images:
- name: ${ECR_URL}/devops-project-backend
  newName: ${ECR_URL}/devops-project-backend
  newTag: c2e4fae52083d95a76c65ad4c0e64e877acc8586
- name: ${ECR_URL}/devops-project-frontend
  newName: ${ECR_URL}/devops-project-frontend
  newTag: c2e4fae52083d95a76c65ad4c0e64e877acc8586

commonLabels:
  environment: dev