apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
  labels:
    app: devops-dashboard
type: Opaque
data:
  API_KEY: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="
  DB_PASSWORD: "Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24="